[package]
name = "bose-dfu"
description = "Firmware updater for various Bose devices"
version = "0.1.0"
authors = ["Thomas Hebb <tommyhebb@gmail.com>"]
edition = "2018"

[dependencies]
hidapi = "1.2"
anyhow = "1.0"
thiserror = "1.0"
num_enum = "0.5"
byteorder = "1.3"
log = "0.4"
env_logger = "0.9"
crc32fast = "1.2"

# Only required for binary
clap = { version = "3.1", features = ["derive"] }
