[package]
name = "bose-dfu"
version = "0.1.0"
authors = ["Thomas Hebb <tommyhebb@gmail.com>"]
edition = "2018"

[dependencies]
hidapi = "1.2"
structopt = "0.3"
anyhow = "1.0"
thiserror = "1.0"
num_enum = "0.5"
byteorder = "1.3"
